apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-consumer-config
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: Production

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: payments
