apiVersion: v1
kind: Secret
metadata:
  name: payments-consumer-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=gamesdb;Username=admin;Password=123456"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
